/**
 * Profile compiler CLI.
 *
 *   build   validate, then write the website's public JSON and the twin's context module
 *   check   validate only
 *   export  write the full Markdown export (includes private data) to the given path
 *
 * Profile lookup order: $PROFILE_PATH → ../dan-profile/profile.yaml → profile/profile.example.yaml
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { loadProfile, projectFor, ProfileError, renderFullMarkdown, renderTwinContext } from "./compile.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

function resolveProfilePath(): string {
  const candidates = [
    process.env.PROFILE_PATH,
    join(root, "../dan-profile/profile.yaml"),
    join(root, "profile/profile.example.yaml"),
  ].filter((p): p is string => Boolean(p));
  const found = candidates.find((p) => existsSync(p));
  if (!found) throw new ProfileError(`No profile found. Tried:\n${candidates.join("\n")}`);
  if (found.endsWith("profile.example.yaml")) console.warn("⚠  Using profile/profile.example.yaml (set PROFILE_PATH for the real profile)");
  return found;
}

function write(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`  wrote ${path.replace(root, ".")}`);
}

function main() {
  const [cmd = "build", arg] = process.argv.slice(2);
  const path = resolveProfilePath();
  const profile = loadProfile(readFileSync(path, "utf8"));
  console.log(`✓ ${path} is valid (${profile.projects.length} projects, ${profile.experience.length} roles)`);

  if (cmd === "check") return;

  if (cmd === "build") {
    write(join(root, "apps/web/src/generated/profile.json"), JSON.stringify(projectFor(profile, "public"), null, 2));
    const context = renderTwinContext(profile);
    write(
      join(root, "workers/api/src/generated/twin-context.ts"),
      `// Generated by packages/profile. Do not edit.\nexport const TWIN_NAME = ${JSON.stringify(profile.identity.name)};\n` +
        `export const TWIN_VOICE = ${JSON.stringify(profile.twin.voice)};\n` +
        `export const TWIN_CONTEXT = ${JSON.stringify(context)};\n` +
        `export const INTEGRATIONS = ${JSON.stringify(profile.integrations)} as const;\n`,
    );
    return;
  }

  if (cmd === "export") {
    if (!arg) throw new ProfileError("usage: npm run profile:export -- <output.md>");
    write(resolve(process.cwd(), arg), renderFullMarkdown(profile));
    return;
  }

  throw new ProfileError(`unknown command "${cmd}" (expected build | check | export)`);
}

try {
  main();
} catch (err) {
  console.error(err instanceof ProfileError ? `✗ ${err.message}` : err);
  process.exit(1);
}
